# -*- mode: ruby -*-
# vi: set ft=ruby :
#

VAGRANTFILE_DIR = File.dirname(__FILE__)
PUPPET_MODULE_DIR = VAGRANTFILE_DIR
SRC_DIR = Pathname(VAGRANTFILE_DIR).parent()

# Vagrantfile API version
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/debian-7.8-64-puppet"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  #config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.network :private_network, ip: "192.168.200.10"
  config.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: 2222, auto_correct: true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.

  config.vm.synced_folder SRC_DIR, '/src'
  config.vm.hostname = "phpvirtualbox"
  config.vm.provision :puppet do |puppet|
     puppet.options = "--verbose --debug"
     puppet.module_path = PUPPET_MODULE_DIR
     puppet.manifests_path = "./"
     puppet.manifest_file  = "vagrant.pp"
     #puppet.hiera_config_path = PUPPET_REPO_DIR.join('hiera.yaml')
   end
end
