# -*- mode: ruby -*-
# vi: set ft=ruby :
#

VAGRANTFILE_DIR = Pathname(File.dirname(__FILE__))
SRC_DIR = Pathname(VAGRANTFILE_DIR).parent()

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "phpvirtualbox"

  config.vm.box = "puppetlabs/debian-7.8-64-puppet"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.network :private_network, ip: "192.168.200.10"
  config.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true

  config.vm.synced_folder SRC_DIR, '/src'
  config.vm.synced_folder VAGRANTFILE_DIR, '/etc/puppet/hieradata'
  
  config.vm.provision :shell do |shell|
  shell.inline = "mkdir -p /etc/puppet/modules;
      puppet module install puppetlabs-apt;
      puppet module install puppetlabs/apache"
  end
  
  config.vm.provision :puppet do |puppet|
     puppet.options = "--verbose --debug"
     puppet.module_path = String(VAGRANTFILE_DIR)
     puppet.manifests_path = String(VAGRANTFILE_DIR)
     puppet.manifest_file  = "vagrant.pp"
   end
end
